version: '3.7'
services:
     database:
          image: mysql
          ports:
            - 3306:3306
            - 33060:33060
          container_name: dbserver
          environment:
            - MYSQL_DATABASE=book
            - MYSQL_ROOT_PASSWORD=123root
            - MYSQL_USER=appbuser
            - MYSQL_PASSWORD=appbpass
     bookmanagementservice:
          image: bookmangimg
          container_name: bookmanagement
          ports:
            - 7001:8080
          environment:
            - mysqlHost=dbserver
            - mysqlPort=3306
            - mysqlDatabase=book
            - mysqlUser=appbuser
            - mysqlPass=appbpass
          links:
            - database
     bookstoreservice:
          image: bookstimg
          container_name: bookstore
          ports:
            - 7002:8080
          environment:
            - bookmanagementhost=http://bookmanagement:7001
          links:
            - bookmanagementservice