version: '3.7'
services:
     database:
          image: mysql
          ports:
            - 3306:3306
          container_name: mysqlserver
          environment:
            - MYSQL_DATABASE=book
            - MYSQL_ROOT_PASSWORD=123root
     bookmanagementservice:
          image: bookmanagement
          container_name: bookmanagement
          ports:
            - 7001:8080
          environment:
            - mysqlHost=mysqlserver
            - mysqlPort=3306
            - mysqlDatabase=book
            - mysqlUser=root
            - mysqlPass=123root
          links:
            - database
     bookstoreservice:
          image: bookstore
          container_name: bookstore
          ports:
            - 7002:8080
          environment:
            - bookmanagementhost=bookmanagement:8080
          links:
            - bookmanagementservice