version: '3.7'
services:
     database:
          image: mysql
          ports:
            - 3306:3306
            - 33060:33060
          hostname: dbserver
          environment:
            - MYSQL_DATABASE=book
            - MYSQL_ROOT_PASSWORD=123root
            - MYSQL_USER=appbuser
            - MYSQL_PASSWORD=appbpass
     bookmanagementservice:
          image:bookmangimg
          ports:
            - 7001:8080
          hostname: bookmanagement
          environment:
            - mysqlHost:dbserver
            - mysqlPort:3306
            - mysqlDatabase:book
            - mysqlUser:appbuser
            - mysqlPass:appbpass
          depends_on:
            - database
     bookstoreservice:
          image: bookstimg
          ports:
            - 7002:8080
          environment:
            - bookmanagementhost=http://bookmanagement
          depends_on:
            - bookmanagementservice