apiVersion: v1
kind: Service
metadata:
     name: booksto-svc
     labels:
          app: booksto-app
          tier: frontend
spec:
     type: NodePort
     ports:
          - nodePort: 31001
            port: 8080
            targetPort: 8080
     selector:
          app: booksto-app
          tier: frontend
