apiVersion: v1
kind: Service
metadata:
     name: mysql-svc
     labels:
          app: mysql-db
          tier: backend
spec:
     ports:
          - port: 3306
            targetPort: 3306
     type: ClusterIP
     selector:
          app: mysql-db
          tier: backend
